baseurl = "https://gophercon.sg/"
languageCode = "en-us"
title = "GopherCon Singapore"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "GopherCon Singapore"
	description = "gophercon singapore golang conference go"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "GoSG"

		[params.navigation.links]
			#about     = "About"
			speakers  = "Schedule"
			venue     = "Venue"
			events    = "Events"
			partners  = "Partners"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		buttonText = "Register"

	# About section
	[params.about]
    headline    = "The inaugural Go conference in Singapore!"


	# Speakers section
	[params.speakers]
		# headline = "At your service"

        [[params.speakers.list]]
            profile-img = "robert"
            title = "Robert Griesemer"
            description = "Hacker"

        [[params.speakers.list]]
            title = "Dave Cheney"
            description = "Hacker"

        [[params.speakers.list]]
          title = "Brad Fitzpatrick"
          description = "Hacker"

        [[params.speakers.list]]
            title = "William Kennedy"
            description = "Hacker"

        [[params.speakers.list]]
            title = "You?"
            description = "Submit a [CFP](https://www.papercall.io/gopherconsg2016)"

  [params.venue]
      headline    = "We've got what you need!"

  [params.events]
      headline    = "We've got what you need!"
      description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
      buttonText  = "Get started!"

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "The Venue"

		[params.aside.button]
      # Get directions

	# Partners section
	[params.partners]
		#headline = "Proudly sponsored by:"
		headline = "Sponsors"
		description = "Interested in becoming a sponsor? [Get in touch](//)"

	# Footer section
	[params.credits]
    description = "hello@gophercon.sg"
